#**AICP EDA Internship 3.0 Task Week 1**


1. **Create an Array of All Even Integers from 30 to 70**

In [3]:
import numpy as np

even_integers = np.arange(30, 71, 2)
print("Array of even integers from 30 to 70:")
print(even_integers)

Array of even integers from 30 to 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


2. **Generate an Array of 15 Random Numbers from a Standard Normal Distribution**


In [7]:
import numpy as np

random_numbers = np.random.randn(15)
print("Array of 15 random numbers from a standard normal distribution:")
print(random_numbers)

Array of 15 random numbers from a standard normal distribution:
[-1.34400634 -0.33983763  0.84710383 -0.53752537 -0.67261719 -1.63160033
  0.51161812  0.30813556  0.17353145  0.42159574 -0.38444007 -0.61243245
 -0.03588688 -0.46094983 -0.10531341]


3. **Compute the Cross-Product of Two Matrices**


In [8]:
import numpy as np

# Define two matrices
matrix_a = np.array([[1, 2, 3], [4, 5, 6]])
matrix_b = np.array([[7, 8, 9], [10, 11, 12]])

# Compute the cross product
cross_product = np.cross(matrix_a, matrix_b)
print(cross_product)


[[-6 12 -6]
 [-6 12 -6]]


4. **compute the determinant of an array using NumPy**

In [9]:
import numpy as np

# Define a square matrix
square_matrix = np.array([[4, 2], [3, 1]])

# Calculate its determinant
determinant = np.linalg.det(square_matrix)
print(determinant)

-2.0


5. **3x3x3 Array with Random Values**

In [10]:
import numpy as np

# Summon a 3x3x3 array with random values
array_3x3x3 = np.random.random((3,3,3))
print(array_3x3x3)

[[[0.94599815 0.47398357 0.67067798]
  [0.20565152 0.03754867 0.20473937]
  [0.69018811 0.48405117 0.95095318]]

 [[0.17819183 0.18787135 0.89235114]
  [0.70593823 0.56560168 0.83425618]
  [0.19124785 0.76435035 0.2962919 ]]

 [[0.10754544 0.30412936 0.36135843]
  [0.0112947  0.25227948 0.46843689]
  [0.87966385 0.89293789 0.89877949]]]


6. **5x5 Array with Random Values and Min/Max Values**

In [11]:
import numpy as np

# Create a 5x5 array with random values
array_5x5 = np.random.random((5,5))
print("5x5 Array with Random Values:")
print(array_5x5)

# Find the minimum and maximum values
min_value = np.min(array_5x5)
max_value = np.max(array_5x5)
print(f"Minimum Value: {min_value}")
print(f"Maximum Value: {max_value}")

5x5 Array with Random Values:
[[0.95408016 0.16701431 0.86434359 0.61039279 0.38947197]
 [0.42092571 0.27424534 0.10866232 0.678215   0.16388894]
 [0.28888935 0.82649029 0.30273682 0.31272149 0.43137331]
 [0.54793993 0.01335567 0.89954528 0.90714496 0.43909899]
 [0.3198955  0.43901758 0.8528212  0.14576117 0.74743181]]
Minimum Value: 0.013355674679683682
Maximum Value: 0.9540801604432497


7. **Mean, Standard Deviation, and Variance Along the Second Axis**

In [12]:
import numpy as np

# Given array
given_array = np.random.random((5,5))
print("Given Array:")
print(given_array)

# Compute the mean along the second axis
mean = np.mean(given_array, axis=1)
print(f"Mean: {mean}")

# Compute the standard deviation along the second axis
std_dev = np.std(given_array, axis=1)
print(f"Standard Deviation: {std_dev}")

# Compute the variance along the second axis
variance = np.var(given_array, axis=1)
print(f"Variance: {variance}")

Given Array:
[[0.34017835 0.64769802 0.47088183 0.35072188 0.62457318]
 [0.75637647 0.99110967 0.32048432 0.81510767 0.78285013]
 [0.88707997 0.81338943 0.23272494 0.51524182 0.94897962]
 [0.51655096 0.62472328 0.79121729 0.10877644 0.40893235]
 [0.22664195 0.93264428 0.30586208 0.05088657 0.36569482]]
Mean: [0.48681065 0.73318565 0.67948316 0.49004006 0.37634594]
Standard Deviation: [0.13048998 0.2220643  0.26841155 0.22868779 0.29761867]
Variance: [0.01702763 0.04931256 0.07204476 0.05229811 0.08857687]
